name: Test execution

on:
  pull_request:
    branches:
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    # let's make sure our tests pass on Chrome browser
    name: Test
    env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Tests
        run: |
          echo ${{ github.ref }}
          echo ${{ github.base_ref }}
          echo ${{ github.head_ref }}
          echo $(git rev-list --left-right --count refs/heads/${{ github.base_ref }}...refs/heads/${{ github.head_ref }} | head -n1 | awk '{print $1;}')
